name: PerRegionChat
version: 1.3
main: com.craftec.perregionchat.PerRegionChat
api-version: 1.13
depend: [WorldGuard]
authors: [Sentropic]
description: Configure a WorldGuard region to have a separate chat from the rest of the world.
commands:
  prc:
    description: Main plugin command
    permission: perregionchat.command.reload
    usage: "Command usage: /prc reload"
